scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['host.docker.internal:9090']

  - job_name: 'api-server'
    scrape_interval: 5s
    static_configs:
    - targets: ['host.docker.internal:9000']